# Generated by Django 4.2.1 on 2023-05-21 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 9, 35, 26, 283901, tzinfo=datetime.timezone.utc)),
        ),
    ]
