# Generated by Django 4.2.1 on 2023-05-21 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_post_data_utworzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 10, 8, 1, 662264, tzinfo=datetime.timezone.utc)),
        ),
    ]
