# Generated by Django 4.2.1 on 2023-05-21 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_post_data_utworzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 10, 10, 47, 819181, tzinfo=datetime.timezone.utc)),
        ),
    ]
