# Generated by Django 4.2.1 on 2023-06-08 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_post_status_alter_post_data_utworzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 19, 27, 50, 67442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('very important', 'Very Important'), ('important', 'Important'), ('not as important', 'Not as Important'), ('not important', 'Not Important')], default='draft', max_length=20),
        ),
    ]
