# Generated by Django 4.2.1 on 2023-06-08 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_post_data_utworzenia_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='priorytet',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 19, 35, 21, 622816, tzinfo=datetime.timezone.utc)),
        ),
    ]
