# Generated by Django 4.2.1 on 2023-06-08 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_status_post_priorytet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 19, 38, 11, 359608, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='priorytet',
            field=models.CharField(choices=[('very important', 'Bardzo Ważne'), ('important', 'Ważne'), ('not as important', 'Nie tak ważne'), ('not important', 'Nieważne')], default='draft', max_length=20),
        ),
    ]
