# Generated by Django 4.2.1 on 2023-06-08 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_post_data_utworzenia_alter_post_priorytet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 19, 38, 14, 459872, tzinfo=datetime.timezone.utc)),
        ),
    ]
